export const APP_FETCH_WEATHER_GEO = 'APP/FETCH_WEATHER_GEO'
export const APP_FETCH_WEATHER_GEO_SUCCESS = 'APP/FETCH_WEATHER_GEO_SUCCESS'
export const APP_FETCH_WEATHER_GEO_FAILURE = 'APP/FETCH_WEATHER_GEO_FAILURE'

export const APP_FETCH_FIVE_DAY_GEO = 'APP/FETCH_FIVE_DAY_GEO'
export const APP_FETCH_FIVE_DAY_GEO_SUCCESS = 'APP/FETCH_FIVE_DAY_SUCCESS'
export const APP_FETCH_FIVE_DAY_GEO_FAILURE = 'APP/FETCH_FIVE_DAY_FAILURE'

export const APP_STORE_UPDATE_UNIT = 'APP/STORE_UPDATE_UNIT'
