export const APP_FETCH_WEATHER_CITY = 'APP/FETCH_WEATHER_GEO'
export const APP_FETCH_WEATHER_CITY_SUCCESS = 'APP/FETCH_WEATHER_CITY_SUCCESS'
export const APP_FETCH_WEATHER_CITY_FAILURE = 'APP/FETCH_WEATHER_CITY_FAILURE'

export const APP_FETCH_WEATHER_GEO = 'APP/FETCH_WEATHER_GEO'
export const APP_FETCH_WEATHER_GEO_SUCCESS = 'APP/FETCH_WEATHER_GEO_SUCCESS'
export const APP_FETCH_WEATHER_GEO_FAILURE = 'APP/FETCH_WEATHER_GEO_FAILURE'